# Generated by Django 2.1.1 on 2019-05-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='InEx',
            field=models.TextField(default='Income'),
        ),
    ]
