# Generated by Django 2.1.1 on 2019-05-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userlog_inex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.TextField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('weight', models.TextField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='points',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='weight',
        ),
        migrations.AddField(
            model_name='userlog',
            name='package_id',
            field=models.TextField(default='-'),
        ),
    ]
