# Generated by Django 2.1.1 on 2019-05-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190531_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='weight',
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.TextField(default='', unique=True),
        ),
    ]
