# Generated by Django 2.1.1 on 2019-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_package_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='points',
            field=models.IntegerField(default='0'),
        ),
    ]
