# Generated by Django 2.1.1 on 2019-06-10 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190610_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 9, 10, 49, 148040, tzinfo=utc)),
        ),
    ]
